apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: tecverify-be
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: tecverify-be-deployment
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 10
