version: "3"
services:
    frontend:
        container_name: tecverify-fe
        build:
            context: ./tecverify-fe/tecverify-fe
            dockerfile: Dockerfile
        ports:
            [80:80]
    backend:
        restart: always
        container_name: tecverify-be
        build:
            context: ./tecverify
            dockerfile: Dockerfile
        expose:
            [5000]