version: "3"
services:
    frontend:
        container_name: tecverify-fe
        build:
            context: ./frontend
            dockerfile: Dockerfile
        ports:
            [80:80]
    backend:
        restart: always
        container_name: tecverify-be
        build:
            context: ./backend
            dockerfile: Dockerfile
        ports:
            [5000:5000]