apiVersion: v1
kind: ConfigMap
metadata:
  name: tecverify-fe-config
data:
  app.config.json: |-
    {
    "MAIN_HEADER": "TecVerify",
    "CLIENT_ID": "0oa2dxm3lbONcEqeb5d7",
    "ISSUER": "https://dev-27926041.okta.com/oauth2/aus2dxnjsgiyARX8N5d7",
    "BACK_END_URL": "http://144.126.253.31:3000",
    "FRONT_END_URL": "http://144.126.253.31:3000",
    "AUTHORIZE_TOKEN_TYPE": "idToken",
    "AUTHORIZE_CLAIM_NAME": "Admin",
    "SCOPES": [
        "openid",
        "email"
    ],
    "INSTRUCTIONS_IN_BYPASS_CODE_GENERATOR": [
        "Inform user to click option try another way to open form for entering admin bypass code",
        "Provide the given admin bypass code as generated on the left for respective system"
    ]
    ,
    "INSTRUCTIONS_IN_ADMIN_SECRET": [
        "Inform user to click option try another way to open form for entering admin bypass code."
    ]
    }

# ---

# apiVersion: v1
# kind: ConfigMap
# metadata:
#   name: tecverify-be-config
# data:
#   be-env-file.txt: |-
#     CLIENT_ID=0oa1zfjq06QsFcNG55d7
#     ISSUER=https://dev-27926041.okta.com/oauth2/aus1zfkynokaHgalF5d7
#     AUTHORIZE_TOKEN_TYPE=idToken
#     AUTHORIZE_CLAIM_NAME=Admin
#     SECRETS_FILE=secrets.json
#     LOGGING_LEVEL=DEBUG
#     LOGGING_MAX_BYTES=1048576
#     LOGGING_BACKUP_COUNT=10
#     ENABLE_API_RATE_LIMITS=True
#     API_RATE_LIMITS_PER_HOUR=300
#     API_RATE_LIMITS_PER_MINUTE=30
#     WHITELISTED_IPS=["127.0.0.1"]
#     TZ=Asia/Kolkata
