apiVersion: v1
kind: ConfigMap
metadata:
  name: tecverify-fe-config
data:
  app.config.json: |-
    {
    "MAIN_HEADER": "TecVerify",
    "CLIENT_ID": "0oa164ptl0ySnZSb50h8",
    "ISSUER": "https://tecnics-demo.oktapreview.com",
    "LOGO": "logo.png",
    "BACK_END_URL": "https://146.190.8.122:5000",
    "FRONT_END_URL": "https://146.190.8.122:3000",
    "AUTHORIZE_TOKEN_TYPE": "idToken",
    "AUTHORIZE_CLAIM_NAME": "Admin",
    "SCOPES": [
        "openid",
        "email"
    ],
    "INSTRUCTIONS_IN_BYPASS_CODE_GENERATOR": [
        "Inform user to click option try another way to open form for entering admin bypass code",
        "Provide the given admin bypass code as generated on the left for respective system"
    ]
    ,
    "INSTRUCTIONS_IN_ADMIN_SECRET": [
        "Inform user to click option try another way to open form for entering admin bypass code."
    ]
    }

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: tecverify-be-config
data:
  NAVEEN: masuna
