apiVersion: v1
kind: Service
metadata:
  name: tecverify-fe-dummy-service
spec:
  type: LoadBalancer
  selector:
    app: tecverify-fe-dummy-selector-app
  ports:
    - name: https
      port: 3000
      targetPort: 443

---
# apiVersion: v1
# kind: Service
# metadata: 
#   name: tecverify-be-dummy-service
# spec:
#   type: LoadBalancer
#   selector:
#     app: tecverify-be-dummy-selector-app
#   ports:
#     - name: https
#       port: 5000
#       targetPort: 5000


# Deleted the Deployments, services and creating again.
    
