apiVersion: v1
kind: Service
metadata:
  name: tecverify-fe
spec:
  
  
  selector:
    app: tecverify-fe
  ports:
    - name: https
      protocol: TCP
      
      port: 443
      
      targetPort: 443
      
      
---
apiVersion: v1
kind: Service
metadata: 
  name: tecverify-be
spec:
  type: ClusterIP
  selector:
    app: tecverify-be
  ports:
    - port: 5000  
      targetPort: 5000