apiVersion: v1
kind: Service
metadata:
  name: tecverify-fe
spec:
  type: LoadBalancer
  
  
  selector:
    app: tecverify-fe
  ports:
    
  - name: http
    port: 80
    targetPort: 80

  - name: https
    port: 443
    targetPort: 443
      
---
apiVersion: v1
kind: Service
metadata: 
  name: tecverify-be
spec:
  type: ClusterIP
  selector:
    app: tecverify-be
  ports:
    - port: 5000  
      targetPort: 5000